.PHONY: fibonacci
fibonacci:
	customasm -f hexstr fibonacci.asm -o test.hex
	.\hex2logi test.hex out.hex

.PHONY: li32test
li32test:
	customasm -f hexstr li32test.asm -o test.hex
	.\hex2logi test.hex out.hex

.PHONY: bubblesort
bubblesort:
	customasm -f hexstr bubblesort.asm -o test.hex
	.\hex2logi test.hex out.hex

.PHONY: Fourier
Fourier:
	customasm -f hexstr Fourier.asm -o test.hex
	.\hex2logi test.hex out.hex